### ISSUE TITLE
error if `$HOME/.local/share` not exist

### ISSUE THREAD

**Issue by PinkD** [magnickolas/remindee-bot#2]
https://github.com/magnickolas/remindee-bot/blob/52552ee2365c99a7da1c079fb1594ee6fe3362f3/src/db.rs#L109-L118

`BaseDirs::data_dir`:
- https://docs.rs/directories/latest/directories/struct.BaseDirs.html#method.data_dir

and use `dp_path` here instead of get it again:
https://github.com/magnickolas/remindee-bot/blob/52552ee2365c99a7da1c079fb1594ee6fe3362f3/src/db.rs#L120-L128

**Comment by magnickolas** [comment]
Hello! Thanks for spotting that, I've created a pull request to fix the problem.
