### ISSUE TITLE
Feature Request: Change Reminder when editing the message that created it 

### ISSUE THREAD

**Issue by autoantwort** [magnickolas/remindee-bot#6]
I sometimes create reminders and edit the original message when I realize that I made a mistake, but that currently has no effect. It would be cool if this would work. 
It is probably necessary to save the message id of the original message in the database, maybe also the message id of the bots answer so that the message could also be modified accordingly. 
If this works, it would be also a nice gimmick if you can delete reminders by deleting the message that created the reminder. 
Great Bot!

**Comment by magnickolas** [comment]
Hi @autoantwort, thank you so much for the kind words! I can see your suggestion improving the user experience a lot as well. I actually remember thinking of it myself a while back, but for some reason never got around to implementing it.

I just took a quick look, and the editing part is definitely doable. However, there seems to be no way to tell if the user has deleted their messages through the [bot API](https://core.telegram.org/bots/api#update), at least for now.

I will try to work on this soon!

P.S. for the deletion part I'm thinking of utilizing the reply mechanism: reply to the bot's or your own message with the reminder to delete it.

**Comment by magnickolas** [comment]
The [latest release](https://github.com/magnickolas/remindee-bot/releases/tag/v0.2.9) provides the editing feature and the one for deleting (as was described in the P.S. comment of my previous reply). Let me know if you encounter issues with it.

**Comment by autoantwort** [comment]
Nice, thank you! Btw I also run a "public" instance https://t.me/remindee_cron_bot (I mean all instances are public)

**Comment by magnickolas** [comment]
> Nice, thank you! Btw I also run a "public" instance https://t.me/remindee_cron_bot (I mean all instances are public)

Cool! I've considered running the bot as a service, but had concerns regarding its ability to scale, as the Telegram bot API allows to send around [30 messages per second](https://core.telegram.org/bots/faq#my-bot-is-hitting-limits-how-do-i-avoid-this) to different users, and it should be easy to "ddos" it as well. In the end, notifications of real people might not reach them, which is the worst thing for a reminder bot.

However, there is a common way to create a meta-bot, which asks users to provide a token from botfather for their private bot, and register it to avoid API's rate limits. It would require that meta-bot and some changes in this codebase. Maybe I will get to it one day :sweat_smile:
