### ISSUE TITLE
Create a yearly reminder 

### ISSUE THREAD

**Issue by autoantwort** [magnickolas/remindee-bot#7]
Maybe I am not smart enough but I was not able to create a simply yearly reminder without using the cron syntax. From what I understand it should be possible to do something like `every 01.01. Happy new Year`, but I simply get "Invalid request". Maybe it could also point me to what was wrong 😅

**Comment by magnickolas** [comment]
Hi! For a yearly reminder you need to specify some date that serves as the initial point (like 01.01 you've mentioned), a [date interval](https://remindee-bot.readthedocs.io/en/latest/#recurring-reminders) of 1 year (1year or 1y for short) and time (let be 0:00). E.g, all of the following would notify yearly:
- `01.01/1y 0:00 Happy New Year`
- `01.01-/1y 0:00 Happy New Year` (explicitly specifying the start date and omitting the end one)
- `01.01 every 1year 0:00 Happy New Year`
